### ISSUE TITLE
Rebuild bosh-provisioner

### ISSUE THREAD

**Issue by mehtaphysical** [cppforlife/bosh-provisioner#4]
Can we rebuild assets/bosh-provisioner? Updates have been added (e.g. template names in the job context) that are currently not a part of the built bosh-provisioner under assets.

**Comment by sclevine** [comment]
Done in 61bd817d12d074864d0b64a6eeabc46497b110da.

Also, all of cf-release, diego-release, etcd-release and garden-linux-release should be bosh-provisionable with that binary.
