### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by joshuamckenty** [cppforlife/bosh-provisioner#9]
No updates in 9 months, can you add a note to the README if this is abandonware?

**Comment by cppforlife** [comment]
@joshuamckenty it's maintained to a point that it works for bosh-lite building (github.com/cloudfoundry/bosh-lite).

**Comment by sclevine** [comment]
@joshuamckenty This is also still used to build PCF Dev (for now).

**Comment by joshuamckenty** [comment]
Gotcha, thanks.
